### ISSUE TITLE
mods were unable to merge

### ISSUE THREAD

**Issue by james-zhang-gb** [SilentNightSound/GI-Model-Importer#112]
```bash
Please enter the key that will be used to cycle mods (can also enter this with -k flag, or set later in .ini). Key must be a single letter

k
Parsing ini sections
Traceback (most recent call last):
  File "E:\Games\3dmigoto-for-genshin\3dmigoto\Mods\genshin_merge_mods.py", line 278, in <module>
    main()
  File "E:\Games\3dmigoto-for-genshin\3dmigoto\Mods\genshin_merge_mods.py", line 103, in main
    mod_data = parse_section(section)
  File "E:\Games\3dmigoto-for-genshin\3dmigoto\Mods\genshin_merge_mods.py", line 271, in parse_section
    key, data = line.split("=")
ValueError: too many values to unpack (expected 2)
```
the ini file content were here:
```ini
; Original by SilentNightSound
; Updated by LeoMods to only call the command once per frame on active character HP, adding namespaces, as well as to fix the loading bar issue

namespace=global\HealthBar

[Constants]
global persist $health = -1
global $hpbarCount=0
global $total=100
global $isPartySwapLoadBar=0
global $auxt=0
global $HPActive=0

[Present]
post $auxt=$auxt+1
post $total=$hpbarCount
post $hpbarCount=0
post $isPartySwapLoadBar=0
post $HPActive=0

[ShaderOverrideGroundHealthPS]
hash = 000d2ce199e12697
allow_duplicate_hash=overrule
if $HPActive && ps-t0 == 34 && $isPartySwapLoadBar == 1
	$hpbarCount = $hpbarCount+1
	if $hpbarCount == $total && $auxt%15 == 0
		store = $health, ps-cb0, 33
	endif
endif

[ShaderOverrideMap]
hash = df48ebf15d4e5d80
$isPartySwapLoadBar=1

[TextureOverrideIcons]
hash = ef054414
filter_index = 34
```

**Comment by leotorrez** [comment]
the file you are trying to merge shouldnt need to be added into any kind of merge mod. May you give me more context on what you trying to achieve?
