### ISSUE TITLE
spankbang 방금까지 잘 다운되다가 갑자기 안됩니다.

### ISSUE THREAD

**Issue by pink0258** [SilentNightSound/GI-Model-Importer#118]
5분 0초 뒤 다시 시작: Invalid: [etc] https://spankbang.com/7cu6z/video/fc2+ppv+1485988+personal+shooting+first+shot+sayaka+19+year

version: 3.8e (23-07-25 02:44:56 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / c5bdd7f0e00947d289bc42d9824d5fac
input: https://spankbang.com/7cu6z/video/fc2+ppv+1485988+personal+shooting+first+shot+sayaka+19+year
type: etc
single: True
url: https://spankbang.com/7cu6z/video/fc2+ppv+1485988+personal+shooting+first+shot+sayaka+19+year
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1692060863.8402507 (23-08-15 00:54:23 UTC) - 5s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.07.06
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
extractor: spankbang
get_video: True, https://spankbang.com/7cu6z/video/fc2+ppv+1485988+personal+shooting+first+shot+sayaka+19+year
[debug] [SpankBang] Extracting URL: https://spankbang.com/7cu6z/video/fc2+ppv+1485988+personal+shooting+first+shot+sayaka+19+year
[debug] [SpankBang] 7cu6z: Downloading webpage
get_video: True, https://spankbang.com/7cu6z/video/fc2+ppv+1485988+personal+shooting+first+shot+sayaka+19+year
[debug] [SpankBang] Extracting URL: https://spankbang.com/7cu6z/video/fc2+ppv+1485988+personal+shooting+first+shot+sayaka+19+year
[debug] [SpankBang] 7cu6z: Downloading webpage
get_video: True, https://spankbang.com/7cu6z/video/fc2+ppv+1485988+personal+shooting+first+shot+sayaka+19+year
[debug] [SpankBang] Extracting URL: https://spankbang.com/7cu6z/video/fc2+ppv+1485988+personal+shooting+first+shot+sayaka+19+year
[debug] [SpankBang] 7cu6z: Downloading webpage
get_video: True, https://spankbang.com/7cu6z/video/fc2+ppv+1485988+personal+shooting+first+shot+sayaka+19+year
[debug] [SpankBang] Extracting URL: https://spankbang.com/7cu6z/video/fc2+ppv+1485988+personal+shooting+first+shot+sayaka+19+year
[debug] [SpankBang] 7cu6z: Downloading webpage
ERROR: [SpankBang] 7cu6z: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
get_video: False, https://spankbang.com/7cu6z/video/fc2+ppv+1485988+personal+shooting+first+shot+sayaka+19+year
[debug] [SpankBang] Extracting URL: https://spankbang.com/7cu6z/video/fc2+ppv+1485988+personal+shooting+first+shot+sayaka+19+year
[debug] [SpankBang] 7cu6z: Downloading webpage
get_video: False, https://spankbang.com/7cu6z/video/fc2+ppv+1485988+personal+shooting+first+shot+sayaka+19+year
[debug] [SpankBang] Extracting URL: https://spankbang.com/7cu6z/video/fc2+ppv+1485988+personal+shooting+first+shot+sayaka+19+year
[debug] [SpankBang] 7cu6z: Downloading webpage
get_video: False, https://spankbang.com/7cu6z/video/fc2+ppv+1485988+personal+shooting+first+shot+sayaka+19+year
[debug] [SpankBang] Extracting URL: https://spankbang.com/7cu6z/video/fc2+ppv+1485988+personal+shooting+first+shot+sayaka+19+year
[debug] [SpankBang] 7cu6z: Downloading webpage
get_video: False, https://spankbang.com/7cu6z/video/fc2+ppv+1485988+personal+shooting+first+shot+sayaka+19+year
[debug] [SpankBang] Extracting URL: https://spankbang.com/7cu6z/video/fc2+ppv+1485988+personal+shooting+first+shot+sayaka+19+year
[debug] [SpankBang] 7cu6z: Downloading webpage
ERROR: [SpankBang] 7cu6z: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
stop
Traceback (most recent call last):
 File "C:\Users\Spi\AppData\Local\Temp\_MEI17322\ytdl_1e9d9617\yt_dlp\yt_dlp\extractor\common", line 837, in _request_webpage
   return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
 File "ytdl", line 432, in urlopen
 File "C:\Users\Spi\AppData\Local\Temp\_MEI17322\ytdl_1e9d9617\yt_dlp\yt_dlp\YoutubeDL", line 3863, in urlopen
   return self._opener.open(req, timeout=self._socket_timeout)
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "C:\Users\Spi\AppData\Local\Temp\_MEI17322\ytdl_1e9d9617\yt_dlp\yt_dlp\YoutubeDL", line 1560, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\Spi\AppData\Local\Temp\_MEI17322\ytdl_1e9d9617\yt_dlp\yt_dlp\YoutubeDL", line 1688, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\Spi\AppData\Local\Temp\_MEI17322\ytdl_1e9d9617\yt_dlp\yt_dlp\extractor\common", line 710, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\Spi\AppData\Local\Temp\_MEI17322\ytdl_1e9d9617\yt_dlp\yt_dlp\extractor\spankbang", line 76, in _real_extract
   video_id, headers={'Cookie': 'country=US'})
 File "C:\Users\Spi\AppData\Local\Temp\_MEI17322\ytdl_1e9d9617\yt_dlp\yt_dlp\extractor\common", line 1113, in _download_webpage
   return self.__download_webpage(url_or_request, video_id, note, errnote, None, fatal, *args, **kwargs)
 File "C:\Users\Spi\AppData\Local\Temp\_MEI17322\ytdl_1e9d9617\yt_dlp\yt_dlp\extractor\common", line 1064, in download_content
   res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
 File "C:\Users\Spi\AppData\Local\Temp\_MEI17322\ytdl_1e9d9617\yt_dlp\yt_dlp\extractor\common", line 898, in _download_webpage_handle
   urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
 File "C:\Users\Spi\AppData\Local\Temp\_MEI17322\ytdl_1e9d9617\yt_dlp\yt_dlp\extractor\common", line 855, in _request_webpage
   raise ExtractorError(errmsg, cause=err)
yt_dlp.utils.ExtractorError: [SpankBang] 7cu6z: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "extractor\etc_downloader", line 64, in get_video
 File "decorator", line 232, in fun
 File "constants", line 928, in try_
 File "constants", line 897, in try_
 File "extractor\etc_downloader", line 95, in _get_video
 File "extractor\etc_downloader", line 91, in _get_video
 File "ytdl", line 440, in extract_info
 File "C:\Users\Spi\AppData\Local\Temp\_MEI17322\ytdl_1e9d9617\yt_dlp\yt_dlp\YoutubeDL", line 1549, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\Spi\AppData\Local\Temp\_MEI17322\ytdl_1e9d9617\yt_dlp\yt_dlp\YoutubeDL", line 1578, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 392, in report_error
yt_dlp.utils.DownloadError: ERROR: [SpankBang] 7cu6z: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1354, in start
 File "utils", line 1433, in start_
 File "extractor\etc_downloader", line 28, in read
 File "extractor\etc_downloader", line 76, in get_video
 File "decorator", line 232, in fun
 File "constants", line 928, in try_
 File "constants", line 897, in try_
 File "extractor\etc_downloader", line 95, in _get_video
 File "extractor\etc_downloader", line 91, in _get_video
 File "ytdl", line 440, in extract_info
 File "C:\Users\Spi\AppData\Local\Temp\_MEI17322\ytdl_1e9d9617\yt_dlp\yt_dlp\YoutubeDL", line 1549, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\Spi\AppData\Local\Temp\_MEI17322\ytdl_1e9d9617\yt_dlp\yt_dlp\YoutubeDL", line 1578, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 392, in report_error
yt_dlp.utils.DownloadError: ERROR: [SpankBang] 7cu6z: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

Invalid: fail=True
EOT: https://spankbang.com/7cu6z/video/fc2+ppv+1485988+personal+shooting+first+shot+sayaka+19+year  (4.3s)

**Comment by leotorrez** [comment]
im afraid you are in the wrong github project. the error seems to suggest you shouldve asked at https://github.com/yt-dlp/yt-dlp/issues?q
