### ISSUE TITLE
blender import .ib and .vb file error

### ISSUE THREAD

**Issue by GRemedy** [SilentNightSound/GI-Model-Importer#142]
wrong message is here：
Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blender_3dmigoto_gimi.py", line 2202, in execute
    import_3dmigoto_raw_buffers(self, context, fmt_path, fmt_path, vb_path=vb_path, ib_path=ib_path, vgmap_path=vgmap_path, **migoto_raw_import_options)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blender_3dmigoto_gimi.py", line 2140, in import_3dmigoto_raw_buffers
    obj = import_3dmigoto(operator, context, paths, merge_meshes=False, **kwargs)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blender_3dmigoto_gimi.py", line 945, in import_3dmigoto
    obj.append(import_3dmigoto_vb_ib(operator, context, [p], **kwargs))
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blender_3dmigoto_gimi.py", line 977, in import_3dmigoto_vb_ib
    (blend_indices, blend_weights, texcoords, vertex_layers, use_normals) = import_vertices(mesh, vb)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blender_3dmigoto_gimi.py", line 918, in import_vertices
    import_normals_step1(mesh, data)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blender_3dmigoto_gimi.py", line 719, in import_normals_step1
    l.normal[:] = normals[l.vertex_index]
IndexError: list index out of range

**Comment by SilentNightSound** [comment]
Hard to say without more data yeah - what the error is saying is that it can't read the normal data, most likely because it either doesn't exist or because the length of the data doesn't match the rest (truncated early).

If you are dumping yourself, make sure to dump with no mods active since they can mess with the process.
