### ISSUE TITLE
AttributeError: 'Mesh' object has no attribute 'vertex_layers_float' Help

### ISSUE THREAD

**Issue by Bababa03837** [SilentNightSound/GI-Model-Importer#178]
Python: Traceback (most recent call last):

File "C:\Users\pimpa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blender_3dmigoto_srmi. py", line 2555, in execute

export_3dmigoto_genshin(self, context, object_name, vb_path, ib_path, fmt_path, self.use_foldername,

File "C:\Users\pimpa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blender_3dmigoto_srmi. py", line 1663, in export_3dmigoto_genshin

vertex = blender_vertex_to_3dmigoto_vertex(mesh, obj, blender_lvertex, layout, texcoord_layers)

File "C:\Users\pimpa\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blender_3dmigoto_srmi. py", line 1036, in blender_vertex_to_3dmigoto_vertex

if 'POSITION.w' in mesh.vertex_layers_float:

AttributeError: 'Mesh' object has no attribute 'vertex_layers_float'

**Comment by kakashisensei20** [comment]
Can also confirm. Seems to be issue with blender gimi python script for blender 4.x. Using it on blender 3.5 and 3.6 works fine. If you need to  open a blender 4.0 file, use blender 3.6.

**Comment by SilentNightSound** [comment]
It's a blender 4.0 issue yeah. There is an updated script in the AGMG discord, but I haven't had a chance to push the changes here too yet. Either grab the new one from AGMG or stick to blender 3.6 and below for now

**Comment by XingZem0928** [comment]
> 是的，这是一个搅拌机 4.0 问题。AGMG discord 中有一个更新的脚本，但我还没有机会在这里推送更改。要么从 AGMG 获取新的，要么暂时坚持使用 Blender 3.6 及更低版本
But it didn't work if I switched to version 3.6
