### ISSUE TITLE
"tuple index out of range" Blender Plugin Error

### ISSUE THREAD

**Issue by TechnoSchnauzer** [SilentNightSound/GI-Model-Importer#255]
I tried to import a dumped model and got this error.
```
Python: Traceback (most recent call last):
  File "C:\Users\diane\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blender_3dmigoto_gimi.py", line 2133, in execute
    import_3dmigoto(self, context, paths, **keywords)
  File "C:\Users\diane\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blender_3dmigoto_gimi.py", line 945, in import_3dmigoto
    obj.append(import_3dmigoto_vb_ib(operator, context, [p], **kwargs))
  File "C:\Users\diane\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blender_3dmigoto_gimi.py", line 977, in import_3dmigoto_vb_ib
    (blend_indices, blend_weights, texcoords, vertex_layers, use_normals) = import_vertices(mesh, vb)
  File "C:\Users\diane\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blender_3dmigoto_gimi.py", line 881, in import_vertices
    if len(data[0]) == 4:
IndexError: tuple index out of range

```
If the model I was trying to dump's files are important here they are:
[hash.json](https://github.com/user-attachments/files/15515672/hash.json)
[Pointed_Ear_DogHead-ib=6da32782.txt](https://github.com/user-attachments/files/15515673/Pointed_Ear_DogHead-ib.6da32782.txt)
[Pointed_Ear_DogHead-vb0=4ccbe27c.txt](https://github.com/user-attachments/files/15515674/Pointed_Ear_DogHead-vb0.4ccbe27c.txt)

**Comment by leotorrez** [comment]
That blender plugin is somewhat outdated. Use XXMITools instead for blender 3.6 +

make sure to uninstall GIMI, SRMI plugins before hand as this one now includes both in it. https://github.com/leotorrez/XXMITools
