### ISSUE TITLE
addon for blender import not working

### ISSUE THREAD

**Issue by Justus55** [SilentNightSound/GI-Model-Importer#288]
Trying to use V7.0 GIMI Tools with Blender 4.2

When attemting to import \GI-Model-Importer-Assets-main\GI-Model-Importer-Assets-main\PlayerCharacterData\Albedo\, for example, I get no result except this message:

Python: Traceback (most recent call last):
  File "C:\Users\ishol\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\blender_3dmigoto_gimi.py", line 2133, in execute
    import_3dmigoto(self, context, paths, **keywords)
  File "C:\Users\ishol\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\blender_3dmigoto_gimi.py", line 945, in import_3dmigoto
    obj.append(import_3dmigoto_vb_ib(operator, context, [p], **kwargs))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ishol\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\blender_3dmigoto_gimi.py", line 977, in import_3dmigoto_vb_ib
    (blend_indices, blend_weights, texcoords, vertex_layers, use_normals) = import_vertices(mesh, vb)
                                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ishol\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\blender_3dmigoto_gimi.py", line 918, in import_vertices
    import_normals_step1(mesh, data)
  File "C:\Users\ishol\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\blender_3dmigoto_gimi.py", line 717, in import_normals_step1
    mesh.create_normals_split()
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Mesh' object has no attribute 'create_normals_split'

Should I try another Blender version, or maybe I'm just doing something wrong?

**Comment by crabatar** [comment]
I'm running into the same issue, I've decided to try out older versions of Blender, version 4.0.2 does not have this error, but any version after that (4.1.0, 4.1.1, 4.2.0) DOES encounter this error. I'd appreciate if there was a fix at some point but for now using an older version of Blender is at least a temporary fix. [Blender 4.0.2 available here](https://download.blender.org/release/Blender4.0/)

**Comment by leotorrez** [comment]
Use xxmi tools. Is the replacement tool

**Comment by duolaameng903** [comment]
is gimi just not updated anymore at all?

**Comment by leotorrez** [comment]
xxmitools contains GIMI plugin within. Gimi is not supported due to the overlap between the two
