### ISSUE TITLE
genshin_3dmigoto_collect.py don't work

### ISSUE THREAD

**Issue by QingCheZhang** [SilentNightSound/GI-Model-Importer#318]
```
PS F:\3dmigoto> python genshin_3dmigoto_collect.py -vb 5d75c166 -n character_name --has_normalmap
Looking for most recent frame dump folder
Found! Folder: FrameAnalysis-2024-10-21-232520
Creating output folder
Searching for VB corresponding with root VS
WARNING: Unable to find root position and blend VB. Assuming none exist and continuing

Found first VS: d0c680ab5914dcea
Traceback (most recent call last):
  File "F:\3dmigoto\genshin_3dmigoto_collect.py", line 708, in <module>
    main()
  File "F:\3dmigoto\genshin_3dmigoto_collect.py", line 58, in main
    relevant_ids, first_vss = collect_relevant_ids(frame_dump_folder, args.vb)
  File "F:\3dmigoto\genshin_3dmigoto_collect.py", line 343, in collect_relevant_ids
    vertex_count = int([x for x in f.readlines() if "vertex count:" in x][0].split(": ")[1])
UnicodeDecodeError: 'gbk' codec can't decode byte 0xc0 in position 12: illegal multibyte sequence
```
I don't knok why this happen, it seems like a compilation error. And the warning massage occurs“WARNING: Unable to find root position and blend VB. Assuming none exist and continuing”, It seems that the files in the FrameAnalysis-2024-10-21-232520 folder are all shortcuts. When I remove the .lnk suffix, the warning disappears. However, this is obviously incorrect because .lnk files are in binary format, and removing the suffix is meaningless. blow is files in FrameAnalysis-2024-10-21-232520
<img width="619" alt="image" src="https://github.com/user-attachments/assets/a6ff8160-b6fb-4ff1-935d-a8579bb9a800">

**Comment by leotorrez** [comment]
https://github.com/Petrascyll/gui_collect is the more advanced version of this tool. I recommend using it instead
