### ISSUE TITLE
not getting weights

### ISSUE THREAD

**Issue by YumAlpha** [SilentNightSound/GI-Model-Importer#62]
i know im trying something that isnt really supposed to work but im trying to use it on another game that is similar in terms of the way its built to genshin, but when i try to gett the model from the frame analysis dump using the collect python script i get the model but it has no weights, is there a way i can maybe fix that?

log from collect:
[test.txt](https://github.com/SilentNightSound/GI-Model-Importer/files/10514863/test.txt)

**Comment by SilentNightSound** [comment]
The collect script was specifically designed for genshin, so it has several patterns hard-coded in and probably won't work without tweaks with other games by default. I would recommend by looking through the frame analysis folder and seeing if you can collect the data by hand - once you understand more about what the format of the game you are looking at is like, you can compare it to genshin to see where it is the same and where it is different.

**Comment by YumAlpha** [comment]
ye i looked and seems like the collect script was leaving out the blend and tangent form the original file, but if i try to import the original  vb and ib with the full info into blender i get a error of
```
Python: Traceback (most recent call last):
  File "C:\Users\roei\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender_3dmigoto_gimi.py", line 1951, in execute
    import_3dmigoto(self, context, paths, **keywords)
  File "C:\Users\roei\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender_3dmigoto_gimi.py", line 940, in import_3dmigoto
    obj.append(import_3dmigoto_vb_ib(operator, context, [p], **kwargs))
  File "C:\Users\roei\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender_3dmigoto_gimi.py", line 969, in import_3dmigoto_vb_ib
    (blend_indices, blend_weights, texcoords, vertex_layers, use_normals) = import_vertices(mesh, vb)
  File "C:\Users\roei\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender_3dmigoto_gimi.py", line 873, in import_vertices
    data = tuple( x[elem.name] for x in vb.vertices )
  File "C:\Users\roei\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender_3dmigoto_gimi.py", line 873, in <genexpr>
    data = tuple( x[elem.name] for x in vb.vertices )
KeyError: 'TANGENT'
```
although it does have it:
[000014-vb0=e93491ba-vs=f8bc49469398b8c9-ps=f4f6550488822b5a.txt](https://github.com/SilentNightSound/GI-Model-Importer/files/10519484/000014-vb0.e93491ba-vs.f8bc49469398b8c9-ps.f4f6550488822b5a.txt)

sorry for asking for help for something not directly related to this project but i dont know where else to ask ;-;

**Comment by YumAlpha** [comment]
i managed to fix the script a little to make it get the wight but now im just getting errors when i try to get it into blender :/


vb after script:
[kfcHead-vb0=e93491ba.txt](https://github.com/SilentNightSound/GI-Model-Importer/files/10520913/kfcHead-vb0.e93491ba.txt)

error:
```
Python: Traceback (most recent call last):
  File "C:\Users\roei\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender_3dmigoto_gimi.py", line 1951, in execute
    import_3dmigoto(self, context, paths, **keywords)
  File "C:\Users\roei\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender_3dmigoto_gimi.py", line 940, in import_3dmigoto
    obj.append(import_3dmigoto_vb_ib(operator, context, [p], **kwargs))
  File "C:\Users\roei\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender_3dmigoto_gimi.py", line 975, in import_3dmigoto_vb_ib
    import_vertex_groups(mesh, obj, blend_indices, blend_weights)
  File "C:\Users\roei\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender_3dmigoto_gimi.py", line 739, in import_vertex_groups
    for i in range(num_vertex_groups):
TypeError: 'float' object cannot be interpreted as an integer
```
